### PR TITLE
Challenges changes and small filter change.

### PR DESCRIPTION
**Pull request by marcusmoller97**
Added directory js/modules. Added all js files to modules except for main.js who was added to js/.
Added createChallengeCards into object challengeSort. Changed its name to createChallengeCardsToFilter.
Moved currentPath into object.
Added if-statement so filterbtn event works in index.html without error messages.

Things to think about where I think problems may arise:

click event to online and onsite buttons from booking.js.
Please check it and think about how we can get those to work with the existing code.

### CODE REVIEW

**Comment by Tobias-hubs** [comment]
Good work! 
we will figure something out about the click events

**Review by Klumpish — COMMENTED** [review]
looks good, good structure.

**Comment by Jorlindstrom** [comment]
Good structure. Is booking.js a module is´nt it just a js-file?

**Review by Klumpish — APPROVED** [review]
looks good approved!

**Review by Jorlindstrom — APPROVED** [review]

**Pull request merged**
