### PR TITLE
About.html with some style

### PR DESCRIPTION
**Pull request by marcusmoller97**
Added a about.html page
Added style
Not sure about bem naming so maybe check over
Might be some minor style that looks ugly but as a first draft I think it's okay.

### CODE REVIEW

**Review by Klumpish — APPROVED** [review]
i like it, but i feel that i might be a bit bright with all the white.
Other then that great job =)

**Comment by Jorlindstrom** [comment]
Good work Ned som space in the bottom on why us in mobile stage.

**Review by jennymakki — APPROVED** [review]
Wow, well done! The naming with BEM looks good and well structured.

**Review by Tobias-hubs — APPROVED** [review]
Very good job, looking great. Have tested it out thumbs up.

**Pull request merged**
