### PR TITLE
Added OG data for title

### PR DESCRIPTION
**Pull request by Klumpish**
Added a new title to the og meta data

### CODE REVIEW

**Comment by Jorlindstrom** [comment]
Isn't that too kind?

**Comment by jennymakki** [comment]
Maybe the title shouldn't include 'best' but instead something more descriptive?

**Comment by Tobias-hubs** [comment]
Maybe we could discuss the naming of the title. But good initiative

**Comment by Klumpish** [comment]
good call tobias lets get on that!

**Comment by marcusmoller97** [comment]
Looks good, I like the name. But maybe other enterprises don't. Otherwise great work!

**Pull request merged**
